# Generated by Django 3.1.5 on 2021-01-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptrecord',
            name='script_id',
            field=models.CharField(default='-', max_length=64),
        ),
    ]
