# Generated by Django 3.1.5 on 2021-01-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_scriptrecord_script_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptrecord',
            name='script_id',
            field=models.CharField(blank=True, default='-', max_length=64),
        ),
    ]
