# Generated by Django 3.1.5 on 2021-01-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_auto_20210121_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptrecord',
            name='path',
            field=models.CharField(blank=True, default='-', max_length=128),
        ),
        migrations.AlterField(
            model_name='scriptrecord',
            name='name',
            field=models.CharField(default='-', max_length=64),
        ),
    ]
