# Generated by Django 3.1.5 on 2021-01-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_auto_20210121_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptrecord',
            name='last_time_used',
            field=models.CharField(blank=True, default='-', max_length=64),
        ),
    ]
